# Generated by Django 5.2 on 2025-09-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlimit',
            options={'verbose_name': 'Limite de Colaboradores', 'verbose_name_plural': 'Limites de Colaboradores'},
        ),
        migrations.AlterField(
            model_name='userlimit',
            name='can_create_users',
            field=models.BooleanField(default=True, help_text='Se este usuário tem permissão para criar novos colaboradores', verbose_name='Pode criar colaboradores'),
        ),
        migrations.AlterField(
            model_name='userlimit',
            name='max_users',
            field=models.PositiveIntegerField(default=2, help_text='Número máximo de colaboradores que este usuário pode criar', verbose_name='Máximo de Colaboradores'),
        ),
    ]
