# Generated by Django 5.2 on 2025-09-01 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_alter_userlimit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario_colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pertence_a', to=settings.AUTH_USER_MODEL)),
                ('usuario_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'unique_together': {('usuario_principal', 'usuario_colaborador')},
            },
        ),
    ]
