# Generated by Django 5.2 on 2025-09-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('vendas', 'Vendas'), ('estoque', 'Estoque'), ('financeiro', 'Financeiro'), ('clientes', 'Clientes'), ('relatorios', 'Relatórios')], max_length=20)),
                ('pode_ver', models.BooleanField(default=False, verbose_name='Pode Ver')),
                ('pode_editar', models.BooleanField(default=False, verbose_name='Pode Editar')),
                ('pode_excluir', models.BooleanField(default=False, verbose_name='Pode Excluir')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='colaborador.colaborador')),
            ],
            options={
                'unique_together': {('colaborador', 'modulo')},
            },
        ),
    ]
