# Generated by Django 5.2 on 2025-08-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notavenda_desconto_notavenda_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notavenda',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária')], max_length=20),
        ),
    ]
