# Generated by Django 5.2 on 2025-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notavenda_usuario_executante_alter_categoria_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária')], default='dinheiro', max_length=15),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='tipo',
            field=models.CharField(choices=[('cadastro', 'Cadastro Inicial'), ('entrada', 'Entrada Avulsa'), ('saida', 'Saída')], max_length=8),
        ),
    ]
