# Generated by Django 5.2 on 2025-10-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_perfil_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='Nome',
        ),
    ]
