# Generated by Django 5.2 on 2025-10-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_user_perfil_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='Nome',
            field=models.CharField(max_length=100),
        ),
    ]
