# Generated by Django 5.2 on 2026-07-16 12:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_perfil_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sku_base',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='tem_variacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(blank=True, default='UN', max_length=20),
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantidade', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='core.produto')),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_venda', to='core.produtovariacao'),
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='core.produtovariacao'),
        ),
        migrations.CreateModel(
            name='TipoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_variacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='tipos_variacao',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='core.tipovariacao'),
        ),
        migrations.CreateModel(
            name='ValorVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='core.tipovariacao')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('tipo', 'valor')},
            },
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='valores',
            field=models.ManyToManyField(related_name='produto_variacoes', to='core.valorvariacao'),
        ),
    ]
