# Generated by Django 5.2 on 2026-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_produto_sku_base_produto_tem_variacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='tipo',
            field=models.CharField(choices=[('cadastro', 'Cadastro Inicial'), ('entrada', 'Entrada Avulsa'), ('saida', 'Saída'), ('correcao', 'Correção de Estoque')], max_length=8),
        ),
    ]
