# Generated by Django 5.2 on 2026-07-16 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_movimentoestoque_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEstoqueBaixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('limite_estoque_baixo', models.PositiveIntegerField(default=5, help_text='Quantidade máxima para considerar estoque baixo')),
                ('dias_movimentacao', models.PositiveIntegerField(default=30, help_text='Dias para filtrar última movimentação no dashboard')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Estoque Baixo',
                'verbose_name_plural': 'Configurações de Estoque Baixo',
            },
        ),
    ]
