# Generated by Django 5.2 on 2026-07-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configestoquebaixo',
            name='dias_validade_orcamento',
            field=models.PositiveIntegerField(default=15, help_text='Dias de validade padrão para orçamentos'),
        ),
    ]
