# Generated by Django 5.2 on 2026-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_configestoquebaixo_dias_validade_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
