# Generated by Django 5.2 on 2026-07-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_produto_preco_compra_produtovariacao_preco_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='notavenda',
            name='acrescimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='notavenda',
            name='operadora_cartao',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notavenda',
            name='parcelas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notavenda',
            name='taxa_operadora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='notavenda',
            name='total_com_acrescimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
