# Generated by Django 5.2 on 2026-07-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_campos_cartao_credito_nota_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('taxa_credito', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxa_debito', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxa_pix', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='notavenda',
            name='maquina_cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.maquinacartao'),
        ),
    ]
