# Generated by Django 5.2 on 2026-07-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_maquina_cartao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maquinacartao',
            options={'verbose_name': 'Máquina de Cartão', 'verbose_name_plural': 'Máquinas de Cartão'},
        ),
        migrations.RemoveField(
            model_name='maquinacartao',
            name='taxa_credito',
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='parcelas_sem_juros',
            field=models.CharField(default='1', help_text='Parcelas isentas de juros, separadas por vírgula. Ex: 1,2,3', max_length=50),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_10x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 10x (%)'),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_11x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 11x (%)'),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_12x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 12x (%)'),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_1x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 1x (%)'),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_2x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 2x (%)'),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_3x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 3x (%)'),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_4x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 4x (%)'),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_5x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 5x (%)'),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_6x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 6x (%)'),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_7x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 7x (%)'),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_8x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 8x (%)'),
        ),
        migrations.AddField(
            model_name='maquinacartao',
            name='taxa_9x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa 9x (%)'),
        ),
        migrations.AlterField(
            model_name='maquinacartao',
            name='taxa_debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa Débito (%)'),
        ),
        migrations.AlterField(
            model_name='maquinacartao',
            name='taxa_pix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa PIX (%)'),
        ),
    ]
