# Generated by Django 5.2 on 2026-07-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0005_permissaocolaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissaocolaborador',
            name='modulo',
            field=models.CharField(choices=[('vendas', 'Vendas'), ('estoque', 'Estoque'), ('variacao', 'Variações'), ('maquina_cartao', 'Máquinas de Cartão'), ('financeiro', 'Financeiro'), ('clientes', 'Clientes'), ('relatorios', 'Relatórios')], max_length=20),
        ),
    ]
