# Generated by Django 5.2 on 2025-08-28 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movimentoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=datetime.time(0, 41, 46, 567840)),
            preserve_default=False,
        ),
    ]
