# Generated by Django 5.2 on 2025-08-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movimentacao_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='notavenda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='notavenda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('transferencia', 'Transferência Bancária')], max_length=20),
        ),
        migrations.AddField(
            model_name='notavenda',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
        migrations.AddField(
            model_name='notavenda',
            name='total_com_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
