# Generated by Django 5.2 on 2026-05-28 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('acao', models.CharField(choices=[('C', 'Criar / Cadastrar'), ('U', 'Editar / Atualizar'), ('D', 'Excluir'), ('L', 'Login / Acesso')], max_length=1, verbose_name='Ação')),
                ('modulo', models.CharField(max_length=100, verbose_name='Módulo / Setor')),
                ('descricao', models.TextField(verbose_name='Descrição da Alteração')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'ordering': ['-data_hora'],
            },
        ),
    ]
